models:
 - type: main
   engine: openai
   model: gpt-4o
rails:
  input:
    flows:
      - self check input  # Implemented programmatically in actions.py
  output:
    messages:
      blocked: "I'm sorry, I can't respond to that."
core:
  actions_path: actions.py