models:
 - type: main
   engine: openai
   model: gpt-4o
   
# Enhanced rails configuration with additional security settings
rails:
  input:
    flows:
      - self check input  # Now enhanced with LLM-based checking
    
  output:
    messages:
      blocked: "I'm sorry, I can't respond to that due to security constraints."
    
core:
  actions_path: actions.py